### ISSUE TITLE
Failover via LB templates create Azure LB rule pointing to BIG-IP mgmt interface instead of external

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-azure-arm-templates#183]
## Do you already have an issue opened with F5 support?
No

## Description
The failover via lb templates will deploy an Azure LB with two backend pool groups. One backend is the mgmt IP of each BIG-IP. The other backend pool is the external secondary IP of each BIG-IP. The template also created one load balancing rule called "external-access". I however already have access to my mgmt via direct. I do not need to load balance my mgmt connection. 

Asking why this load balancing rule is here instead of an example rule that points to the application stead.

Current:
Azure LB rule has one public IP, points to backend mgmt IP

Expected:
Azure LB rule has one public IP, points to backend external secondary IP (data plane)

Workaround:
After deployment, manually (or via orchestration) create new load balancing rule for application access. Or...alternatively, modify the existing LB rule and swap the loadBalancerMgmtBackEnd pool with the loadBalancerBackEnd pool.
 
## Template
All LB templates

## Severity Level
3

**Comment by shyawnkarim** [comment]
This load balancing rule is here because of the order of operations Azure uses to determine the NAT IP for outbound access.  In the case of no public IP assigned directly to the mgmt interface, and an LB in front of any interface, we needed to create an LB rule pointing to mgmt so that it could onboard BIG-IP.  In your case, you are using a direct public IP for access to mgmt, so that should take precedence over any LB rule.

It's a possible improvement in the template but the logic is very complicated. This issue is now being tracked internally with ID ESECLDTPLT-2043.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-azure-arm-templates-v2).
