### ISSUE TITLE
Please add the ability to deploy an image version of "latest12"

### ISSUE THREAD

**Issue by strtdusty** [F5Networks/f5-azure-arm-templates#40]
## Description
Whenever I deploy a new version 12 BIG IP from my ARM template, I am forced to go lookup the latest image version.  Inevitably the version I have has been replaced by a new version.  You allow for a "latest" tag that picks up version 13's latest and deploys it.  Could you add a "latest12" to pull the latest version 12?

**Comment by edwoodjrjr** [comment]
Hi strdusty, the "latest" choice directly corresponds with the "latest" version in Azure.  When v14 is published, it will become "latest".  The explicit version numbers you see in the template match the version numbers in Azure, and "latest" is going to be the same as the most recent explicit version listed, so you shouldn't need to look anything up.

**Comment by strtdusty** [comment]
We haven't upgraded to 13 yet but periodically create new instances of 12.  Our templates regularly fail because there is a new latest version of **12**.  We do not want to deploy the latest version of 13.

**Comment by edwoodjrjr** [comment]
The previous versions were permanently replaced with 12.1.24 due to a security fix.  Which version of 12 are you running, and what is failing in the deployment?

**Comment by strtdusty** [comment]
Whenever a new image is released, the old image is removed (for 12.1).  If I release with 12.1.23 the release will fail.  Then I have to go to github to find the latest version of the image and update my template.

**Comment by edwoodjrjr** [comment]
Now I understand the issue.  Unfortunately, adding a tag to get the latest version 12 image won't solve the problem.  Since there is no corresponding version for that in Azure, and we have to point to an explicit version number in the VM resource definition, the template would still be broken as soon as the current v12 image is superseded.  I think the intention here is to have users regularly check GitHub for new versions of the templates, however we don't say that directly in the README. We will look into how to handle this better.

**Comment by edwoodjrjr** [comment]
Closing issue as it has been escalated to the solutions team.
