### ISSUE TITLE
Virtual Server IP is not floating to new active unit while failover in a Active/Standby API failover setup

### ISSUE THREAD

**Issue by manigandacharan** [F5Networks/f5-azure-arm-templates#88]
## Description
Hello,  we need some help with an issue we are facing with a 3nic active/standby arm deployment. The deployment goes fine, once deployed, we remove the public IPs mapped on the interfaces of the external, management and VS as our management wants this cluster to have only internal IPs. The VIPs will have a nat on the external facing firewall. LTM LB works fine, however, when we do a forced failover for test purposes, the Virtual Server secondary IP on the external interface of the active unit on azure does not float over to the new active unit.

## Template
https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi, please open a ticket with F5 support on this issue.  Typical causes are incorrect permissions or configuration for service principal, or not having an LTM virtual address matching the IP config secondary IP.

**Comment by ecc256** [comment]
>Typical causes are incorrect permissions or configuration for service principal, or not having an LTM virtual address matching the IP config secondary IP.

I wonder if actions performed by service principal during failover and corresponding errors (if any) logged somewhere on BIG-IP VE?

**Comment by edwoodjrjr** [comment]
Should be in /var/log/cloud/azure/failover.log

**Comment by pvude** [comment]
I have the same issue with the payg template (https://github.com/F5Networks/f5-azure-arm-templates/tree/master/supported/failover/same-net/via-api/n-nic/existing-stack/payg). 
UDR next-hop IP change was successful but move of secondary ip on bigip external interface in azure failed. 
Error message in azure: 
   Error code
     InvalidIPConfigCount
   Message
     Network interface azurewaf-ext1 must have one or more IP configurations.
This is strange, because there are two ip addresses (primary and secondary), and of course only the secondary ip address (=ip address of virtual server) should be moved.

Error message in /var/log/cloud/azure/failover.log:
2018-09-13T09:43:17.181Z info:  Disassociate NIC:  azurewaf-ext1
2018-09-13T09:43:17.342Z error:  Disassociate NIC error:  {"message":"Network interface azurewaf-ext1 must have one or
 more IP configurations.","stack":"Error: Network interface azurewaf-ext1 must have one or more IP configurations.\n
  at /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_modules/azure-arm-network/lib/operations/
networkInterfaces.js:2041:19\n    at retryCallback (/config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure
/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)\n    at retryCallba
ck (/config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/ms-rest
/lib/filters/exponentialRetryPolicyFilter.js:140:9)\n    at /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-li
bs-azure/node_modules/ms-rest-azure/node_modules/ms-rest/lib/filters/rpRegistrationFilter.js:59:14\n    at handleRedir
ect (/config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/ms-res
t/lib/filters/redirectFilter.js:39:9)\n    at /config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_
modules/ms-rest-azure/node_modules/ms-rest/lib/filters/formDataFilter.js:23:14\n    at Request._callback (/config/clou
d/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node_modules/ms-rest-azure/node_modules/ms-rest/lib/requestPipe
line.js:125:16)\n    at Request.self.callback (/config/cloud/azure/node_modules/@f5devcentral/f5-cloud-libs-azure/node
_modules/request/request.js:185:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)","statusC
ode":400,"request":{"rawResponse":false,"queryString":{},"url":"https://management.azure.com/subscriptions/94242550-95
19-4cbd-adc0-7c51ba75819a/resourceGroups/pv-rg-88a/providers/Microsoft.Network/networkInterfaces/azurewaf-ext1?api-ver
sion=2017-10-01","method":"PUT","headers":{"Content-Type":"application/json; charset=utf-8","x-ms-client-request-id":"
1cf4d154-df9b-46cb-9c88-0fb6ede67314","accept-language":"en-US","user-agent":"Node/v4.8.0 (x64-Linux-3.10.0-514.26.2.e
l7.ve.x86_64) ms-rest/2.3.6 ms-rest-azure/2.5.7 azure-arm-network/5.1.0 Azure-SDK-For-Node"},"body":"{\"location\":\"w
esteurope\",\"tags\":{\"application\":\"APP\",\"environment\":\"ENV\",\"group\":\"GROUP\",\"owner\":\"OWNER\",\"cost\"
:\"COST\"},\"properties\":{\"networkSecurityGroup\":{\"id\":\"/subscriptions/94242550-9519-4cbd-adc0-7c51ba75819a/reso
urceGroups/pv-rg-88a/providers/Microsoft.Network/networkSecurityGroups/azurewaf-ext-nsg\"},\"ipConfigurations\":[],\"e
nableIPForwarding\":false}}"},"response":{"body":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidIPConfigCount\",\r\n
  \"message\": \"Network interface azurewaf-ext1 must have one or more IP configurations.\",\r\n    \"details\": []\r\
n  }\r\n}","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"171","content-type":"applicatio
n/json; charset=utf-8","expires":"-1","x-ms-request-id":"d17e8004-807c-482e-9d66-eec517010a75","x-ms-correlation-reque
st-id":"22678650-3ee0-4dac-ac4a-93c52d1159ac","strict-transport-security":"max-age=31536000; includeSubDomains","x-ms-
ratelimit-remaining-subscription-writes":"1199","server":"Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0","x-ms-routing-
request-id":"WESTEUROPE:20180913T094317Z:22678650-3ee0-4dac-ac4a-93c52d1159ac","x-content-type-options":"nosniff","dat
e":"Thu, 13 Sep 2018 09:43:16 GMT","connection":"close"},"statusCode":400},"code":"InvalidIPConfigCount","body":{"code
":"InvalidIPConfigCount","message":"Network interface azurewaf-ext1 must have one or more IP configurations.","details
":[]}}

**Comment by edwoodjrjr** [comment]
@pvude Do you have a virtual address that corresponds to the primary IP address of azurewaf-ext1?

**Comment by pvude** [comment]
You are right: In the beginning by mistake I chose the primary IP of the standby device external interface as a virtual server address and afterwards corrected the virtual server address to be the secondary ip.
I suppose this led to the error.
Can I correct it?

**Comment by edwoodjrjr** [comment]
Yes, all you should need to do is delete the LTM virtual address that matches the primary IP.

**Comment by pvude** [comment]
Unfortunately that didn't help. That's what I tried:
- delete virtual address
- shutdown and restart both bigip vms
- change of external interface ip
But non of these actions resolved the issue. The secondary IP of the external BIGIP interface does not move to the other unit and the error message in Azure remains the same (InvalidIPConfigCount).
Do you have any other idea ?
Otherwise I think I have to rebuild the bigip cluster.

**Comment by edwoodjrjr** [comment]
Hi, did you ever resolve this issue?

**Comment by jsevedge** [comment]
@pvude Is this still an issue for you?

Note: I might suggest deleting the *statusdb* file inside the *data000* -> *failover* container.

**Comment by phanbyte** [comment]
hi, i have the same issue but i think is we missing some configuration in the Tagging part which in the documentation is not very clear.  we able to modify the UDR but to change the secondary ip address is not.  we open a ticket and we have 2 weeks with them unable to resolve the isssue that why i am writing here.

2019-11-20T22:16:02.126Z info:  Performing failover
2019-11-20T22:16:02.128Z info:  Updating route:  route_default.
2019-11-20T22:16:02.142Z info:  Disassociate NICs successful.
2019-11-20T22:16:02.143Z info:  Associate NICs successful.
2019-11-20T22:16:02.152Z info:  Failover finished successfully
2019-11-20T22:16:02.396Z info:  Update route successful:  route_default.

**Comment by shyawnkarim** [comment]
Closing. [Cloud Failover Extension](https://github.com/F5Networks/f5-cloud-failover-extension) is now used for failover.

**Comment by iyyappangopal321** [comment]
hi team am not able to do API failover with this template can any one support - there is no permission issue, only API failover issue facing in BYOL not in Payg template 


https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/failover/same-net/via-api/n-nic/existing-stack/byol

**Comment by iyyappangopal321** [comment]
please suggest post deployment step for below , In Payg bydefault configuration complated automatically.but in BYOL its not have to do manually 


https://github.com/F5Networks/f5-azure-arm-templates/tree/main/supported/failover/same-net/via-api/n-nic/existing-stack/byol
